include ../Makefile

# CC = gcc
#
# CFLAGS = -Wextra -Wall -Wshadow
#
# LIBS = $(shell sdl2-config --cflags --libs) -lm -lpng
#
# main:
# 	$(CC) main.c $(LIBS) $(CFLAGS) -o Build/main
#
# debug: CFLAGS += -O -g3
# debug: main
# 	gdb -ex "set debuginfod enabled off" -ex run ./Build/main
#
# run: main
# 	./Build/main $(ARGS)
